name: localization_helper
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  archive: ^3.4.6
  auto_route: ^7.8.4
  bloc: ^8.1.2
  collection: ^1.17.2
  excel: ^2.1.0
  file_picker: ^6.0.0
  file_saver: ^0.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
